spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
             - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: owner-service
          uri: lb://owner-service
          predicates:
            - Path=/api/owner/**
          filters:
            - StripPrefix=2